import React, { useState } from 'react';
import { X, Plus, Trash } from 'lucide-react';
import { departmentService } from '../../services/departmentService';

interface NewDepartmentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export default function NewDepartmentModal({ isOpen, onClose, onSuccess }: NewDepartmentModalProps) {
  const [formData, setFormData] = useState({
    name: '',
    head: '',
    roles: ['']
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      await departmentService.addDepartment({
        name: formData.name,
        head: formData.head,
        roles: formData.roles.filter(role => role.trim() !== ''), // Remove empty roles
        departmentId: '' // Will be generated by the service
      });

      onSuccess();
      onClose();
      // Reset form
      setFormData({
        name: '',
        head: '',
        roles: ['']
      });
    } catch (err) {
      setError('Failed to create department');
    } finally {
      setLoading(false);
    }
  };

  const addRole = () => {
    setFormData(prev => ({
      ...prev,
      roles: [...prev.roles, '']
    }));
  };

  const removeRole = (index: number) => {
    setFormData(prev => ({
      ...prev,
      roles: prev.roles.filter((_, i) => i !== index)
    }));
  };

  const updateRole = (index: number, value: string) => {
    setFormData(prev => ({
      ...prev,
      roles: prev.roles.map((role, i) => i === index ? value : role)
    }));
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex items-center justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
        <div className="fixed inset-0 transition-opacity bg-gray-500 bg-opacity-75" onClick={onClose} />

        <div className="inline-block overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
          <div className="px-4 pt-5 pb-4 bg-white sm:p-6 sm:pb-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-secondary-900">New Department</h3>
              <button
                onClick={onClose}
                className="p-1 text-secondary-400 hover:text-secondary-500 rounded-full"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Department Name */}
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">
                  Department Name
                </label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              {/* Department Head */}
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">
                  Department Head (Title)
                </label>
                <input
                  type="text"
                  required
                  value={formData.head}
                  onChange={(e) => setFormData(prev => ({ ...prev, head: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              {/* Roles */}
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">
                  Roles
                </label>
                <div className="space-y-2">
                  {formData.roles.map((role, index) => (
                    <div key={index} className="flex gap-2">
                      <input
                        type="text"
                        value={role}
                        onChange={(e) => updateRole(index, e.target.value)}
                        className="flex-1 px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-primary-500"
                        placeholder="Enter role"
                      />
                      {formData.roles.length > 1 && (
                        <button
                          type="button"
                          onClick={() => removeRole(index)}
                          className="p-2 text-red-600 hover:bg-red-50 rounded-lg"
                        >
                          <Trash className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  ))}
                </div>
                <button
                  type="button"
                  onClick={addRole}
                  className="mt-2 text-sm text-primary-600 hover:text-primary-700 font-medium inline-flex items-center gap-1"
                >
                  <Plus className="w-4 h-4" />
                  Add role
                </button>
              </div>

              {error && (
                <div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">
                  {error}
                </div>
              )}

              <div className="flex justify-end gap-3 mt-6">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 text-sm text-secondary-600 hover:text-secondary-700"
                >
                  Close
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50"
                >
                  {loading ? 'Creating...' : 'Save Department'}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
} 